Product-Category/FinalProject/FinalProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
app_name='main'




urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin:index'),
    url(r'^accounts/', include('accounts.urls')), # This needs to be added for each app to get sub URLs
    url(r'^products/', include('products.urls')), # This needs to be added for each app to get sub URLs
    url(r'^categories/', include('categories.urls')), # This needs to be added for each app to get sub URLs

    url(r'^$', views.homepage, name='homepage'), # Homepage
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product-Category/FinalProject/accounts/urls.py
from django.conf.urls import url
from . import views
app_name='accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),

]

Product-Category/FinalProject/categories/urls.py
from django.conf.urls import url
from . import views
app_name='categories'


urlpatterns = [
    url(r'^$', views.categories, name="list"), 
    url(r'^create/$', views.catergory_create, name="create"), 
    url(r'^(?P<slug>[\w-]+)/$', views.catergory_detail), 

]

Product-Category/FinalProject/products/urls.py
from django.conf.urls import url
from . import views
app_name='products'

urlpatterns = [
    url(r'^$', views.product_list, name="list"), 
    url(r'^create/$', views.product_create, name="create"), 
    url(r'^(?P<slug>[\w-]+)/$', views.product_detail, name="detail"), 
]

Product-Category/FinalProject/accounts/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    username = models.CharField(max_length=26)
    password = models.CharField(max_length=26)

    def __str__(self):
        return self.username

Product-Category/FinalProject/categories/models.py
from django.db import models
# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=26, unique=True)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

Product-Category/FinalProject/products/models.py
from django.db import models
from categories.models import Category

# from ..categories.models import Category

# Create your models here.
class Product(models.Model):
    category = models.ForeignKey('categories.Category', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=26,unique=True)
    slug = models.SlugField()
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=6)
    quantity = models.IntegerField()
    sku = models.IntegerField()
    picture = models.ImageField(default='default.png',blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.description[:150] + "..."

Product-Category/FinalProject/categories/forms.py
from django import forms
from .import models

class CreateCategory(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = ['title','slug']
        

Product-Category/FinalProject/products/forms.py
from django import forms
from .import models

class CreateProduct(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['category','title','slug','description','price','quantity','sku','picture']

Product-Category/FinalProject/FinalProject/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    # return HttpResponse("Homepage")
    return render(request,'homepage.html')

 

Product-Category/FinalProject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form' : form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('homepage')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form' : form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('homepage')

Product-Category/FinalProject/categories/views.py
from django.shortcuts import render, redirect
from .models import Category
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms




# Create your views here.

def categories(request):

    categories = Category.objects.all()  #.order_by()
    return render(request,'categories/categories.html', {'categories':categories})

def catergory_detail(request, slug):
    return HttpResponse(slug)


@login_required(login_url="/accounts/login/")
def catergory_create(request):
    if request.method =='POST':
        form = forms.CreateCategory(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('categories:list')
    else:
        form = forms.CreateCategory
    return render(request, 'categories/category_create.html',{'form':form})

Product-Category/FinalProject/products/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms



# Create your views here.

def product_list(request):
    products = Product.objects.all()  #.order_by()
    return render(request,'products/product_list.html', {'products': products})
    
def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    return render(request, 'products/product_detail.html', {'product':product})



@login_required(login_url="/accounts/login/")
def product_create(request):
    if request.method =='POST':
        form = forms.CreateProduct(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('products:list')
    else:
        form = forms.CreateProduct
    return render(request, 'products/product_create.html',{'form':form})

Product-Category/FinalProject/accounts/templates/accounts/accounts.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Accounts</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
</head>

<body>
    <h1>Accounts</h1>

</body>

</html>

Product-Category/FinalProject/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} 
{% block content %}
<div class="d-flex justify-content-center"> 
    <h1>Login</h1>
</div>

<div class="d-flex justify-content-center"> 
    <form class="site-form" action="{% url 'accounts:login'%}" method="post">
        {% csrf_token %}    
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

Product-Category/FinalProject/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} 
{% block content %}
<h1>Sign Up</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}    
    {{form}}
    <input type="submit" name="" value="Sign Up">
</form>

{% endblock %}

Product-Category/FinalProject/categories/templates/categories/categories.html
{% extends 'base_layout.html' %} 

{% block title %}
    <title>Categories</title>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center"> 
        <h1>Catergory List</h1><br/><br/><br/>
    </div><br/>

        {% if user.is_authenticated %}  
            <div class="d-flex justify-content-center"> 
                <a href="{% url 'categories:create' %}"><button type="button" class="btn btn-info space">Add</button></a>
                <a href="{% url 'admin:index' %}"><button type="button" class="btn btn-info space">Edit / Delete</button></a>
            </div>

        {% else %}
            <div class="d-flex justify-content-center"> 
                <p>(To add, edit or delete, you neeed to login)</p>
            </div>
        {% endif %}

    <div class="table-responsive d-flex justify-content-center">
        <table class="table table-striped table-bordered table-hover table-dark table-fit">
            <thead>
                <tr>
                    <th scope="col"><h2>Category Name</h2></th>
                </tr>
            </thead>
            <tbody>

            {% for category in categories %} 
            <tr>
                <td>{{category.title}}</td>
            </tr>
            {% endfor %}
    </div>
{% endblock %}

Product-Category/FinalProject/categories/templates/categories/category_create.html
{% extends 'base_layout.html' %} 

{% block title %}
    <title>Create Category</title>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center"> 
        <h2>Create a New Category</h2>
    </div>
    <div class="d-flex justify-content-center"> 
    
        <form class="site-form" action="{% url 'categories:create'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create"> 
        </form>
    </div>


<script src="/static/slugify.js"></script>


{% endblock %}

Product-Category/FinalProject/products/templates/products/product_create.html
{% extends 'base_layout.html' %} 

{% block title %}
    <title>Create Product</title>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center"> 
        <h2>Create an Awesome New Product</h2>
    </div>
    <div class="d-flex justify-content-center"> 
    
        <form class="site-form " action="{% url 'products:create'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create"> 
        </form>
    </div>


<script src="/static/slugify.js"></script>


{% endblock %}

Product-Category/FinalProject/products/templates/products/product_detail.html
{% extends 'base_layout.html' %} 

{% block title %}
    <title>Product Details</title>
{% endblock %}

{% block content %}
<div class="product-detail"> 
    <div class="product">
        <img src="{{product.picture.url}}"/>
        <h2>{{ product.title }}</h2>
        <p>{{product.category.title}}</p>

        <p>{{product.description}}</p>
        <p>{{product.price}}</p>

    </div>
</div>


{% endblock %}

Product-Category/FinalProject/products/templates/products/product_list.html
{% extends 'base_layout.html' %} 

{% block title %}
    <title>Product List</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center"> 
    <h1>Product List</h1>
</div><br/>

  {% if user.is_authenticated %}  
      <div class="d-flex justify-content-center"> 
          <a href="{% url 'products:create' %}"><button type="button" class="btn btn-info space">Add</button></a>
          <a href="{% url 'admin:index' %}"><button type="button" class="btn btn-info space">Edit / Delete</button></a>
      </div>

  {% else %}
      <div class="d-flex justify-content-center"> 
          <p>(To add, edit or delete, you neeed to login)</p>
      </div>
  {% endif %}

<div class="table-responsive d-flex justify-content-center">
<table class="table table-striped table-bordered table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Category</th>
      <th scope="col" class="maxColWidth">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity in Stock</th>
      <th scope="col">Sku</th>
      <th scope="col">Image</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %} 
    <tr>
      <td scope="row"><a href="{% url 'products:detail' slug=product.slug %}">{{product.title}}</a></td>
      <td><a href="{% url 'products:detail' slug=product.slug %}">{{product.category}}</a></td>
      <td><a href="{% url 'products:detail' slug=product.slug %}">{{product.snippet}}</a></td>
      <td><a href="{% url 'products:detail' slug=product.slug %}">${{product.price}}</a></td>
      <td><a href="{% url 'products:detail' slug=product.slug %}">{{product.quantity}}</a></td>
      <td><a href="{% url 'products:detail' slug=product.slug %}">{{product.sku}}</a></td>
      <td><a href="{% url 'products:detail' slug=product.slug %}"><img class="responsive" src="{{product.picture.url}}"/></a></td>
    </tr>
    {% endfor %}
      
  </tbody>
</table>
</div>




{% endblock %}

Product-Category/FinalProject/products/templates/products/products.html
{% extends 'base_layout.html' %} 

{% block title %}
    <title>Products</title>
{% endblock %}

{% block content %}
    <h1>Product List</h1>
    <div class="products">
        {% for product in products %} 
            <div class="product"> 
                <h2><a href="#">{{product.title}}</a></h2>
                <!-- <p>{{product.category}}</p> -->
                <p>{{product.snippet}}</p>
                <p>{{product.price}}</p>
                <p>{{product.quantity}}</p>
                <p>{{product.sku}}</p>
                <!-- <img {{product.sku}}/> -->
            </div>
        {% endfor %}
    </div>
{% endblock %}

Product-Category/FinalProject/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block title%}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <nav class="d-flex flex-row justify-content-end navBarMod space">
        {% if user.is_authenticated %}  
            <form class=" space" action="{% url 'accounts:logout'%}" method="post">
                {% csrf_token %}
                <button type="subtmit button" class="btn btn-danger"> Logout </button>
            </form>
            <a href="{% url 'homepage' %}"><button type="button" class="btn btn-info  space">Back to Homepage</button></a>
        {% else %}
            <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-primary space">Login</button></a>
            <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-warning space">Signup</button></a>
            <a href="{% url 'homepage' %}"><button type="button" class="btn btn-info space">Back to Homepage</button></a>
        {% endif %}
    </nav>

    <div class="d-flex justify-content-center">
        <a href="{% url 'homepage' %}"><img class="rounded" src="{% static 'logo.png' %}"></a>
    </div> 
    <br/><br/><br/><br/>

        {% block content%}
        {% endblock %}

</body>
</html>

Product-Category/FinalProject/templates/homepage.html
{% extends 'base_layout.html' %} 


{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center"> 
    <div class="d-flex flex-column align-items-center">
        <div class="p-2">
            <h1>Which would you like to view?</h1><br/><br/>
        </div>
        <div class="p-2">
            <a href="{% url 'categories:list' %}"><button type="button" class="btn btn-secondary">Categories</button></a><br/>
        </div>
        <div class="p-2">
            <a href="{% url 'products:list' %}"><button type="button" class="btn btn-secondary">Products</button></a>
        </div>
    </div>
</div>

{% endblock %}