Blog/djangoapp/accounts/urls.py
from django.conf.urls import url
from . import views
app_name='accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),

]

Blog/djangoapp/articles/urls.py
from django.conf.urls import url
from . import views
app_name='articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"), 
    url(r'^create/$', views.article_create, name="create"), 
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"), 



]

Blog/djangoapp/djangoapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')), # This needs to be added for each app to get sub URLs
    url(r'^accounts/', include('accounts.urls')), # This needs to be added for each app to get sub URLs

    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home") # Homepage

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/djangoapp/accounts/models.py
from django.db import models

# Create your models here.

Blog/djangoapp/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User, default=1)
    # add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

Blog/djangoapp/articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

Blog/djangoapp/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form' : form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form' : form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

Blog/djangoapp/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms


# Create your views here.

def article_list(request):

    articles = Article.objects.all()  #.order_by()
    return render(request,'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method =='POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle
    return render(request, 'articles/article_create.html',{'form':form})

Blog/djangoapp/djangoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    # return HttpResponse("Homepage")
    return render(request,'homepage.html')

def about(request):
    # return HttpResponse("About")
    return render(request,"about.html")

Blog/djangoapp/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} 
{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login'%}" method="post">
    {% csrf_token %}    
    {{form}}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" name="" value="Login">
</form>

{% endblock %}

Blog/djangoapp/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} 
{% block content %}
<h1>Sign Up</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}    
    {{form}}
    <input type="submit" name="" value="Sign Up">
</form>

{% endblock %}

Blog/djangoapp/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} 
{% block content %}
    <div class="create-article">
        <h2>Create and Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}

            <input type="submit" value="Create"> 
        </form>

    <div>

<script src="/static/slugify.js"></script>

{% endblock %}

Blog/djangoapp/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} 
{% block content %}
<div class="article-detail"> 
    <div class="article">
        <img src="{{article.thumb.url}}"/>
        <h2>{{ article.title }}</h2>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>

    </div>
</div>


{% endblock %}

Blog/djangoapp/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} 

{% block content %}
    <h1>Article List</h1>
    <div class="articles">
        {% for article in articles%} 
            <div class="article"> 
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
                <p class="author">Added by: {{article.author.username}}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

Blog/djangoapp/templates/about.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
</head>

<body>
    <h1>This is the About</h1>
    <p>Welcome! Enjoy</p>

</body>

</html>

Blog/djangoapp/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<header class="wrapper">
    <h1> <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a></h1>
    <nav>
        <ul>
        {% if user.is_authenticated %}
            <li>
                <form class="logout-link " action="{% url 'accounts:logout'%}" method="post">
                    {% csrf_token %}
                    <button type="submit"> Logout </button>
                </form>
            </li>
            <li><a href="{% url 'articles:create'%} " class="highlight">New Article</a></li>
            {% else %}
        
             <li> <a href="{% url 'accounts:login' %}">Login</a></li>
             <li> <a href="{% url 'accounts:signup' %}">Signup</a></li>
            
            {% endif %}
        </ul>
    </nav>
    </header>
<div class="wrapper">
        {% block content%}
        {% endblock %}
    </div>
</body>
</html>

Blog/djangoapp/templates/homepage.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Homepage</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
</head>

<body>
    <h1>This is the Homepage</h1>
    <p>Welcome to django app</p>

</body>

</html>